### ISSUE TITLE
Enable async mode for jinja2

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-jinja2#152]
Since jinja 2.9 there is async mode: http://jinja.pocoo.org/docs/2.9/api/#async-support

**Comment by jettify** [comment]
@bmwant would you like to take a look?

**Comment by bmwant** [comment]
@jettify sure!

**Comment by asvetlov** [comment]
Summary
-------------

We declined the feature request.
`jinja2` async support is designed badly currently, sorry.
The proper design should support `await` and `async for` directly in the template language.
Without it check for every returned value violates the very important feature of asyncio: all context switch points should be explicitly visible to a developer. Also `jinja2` is significantly slower in async mode, it is the direct consequence of checking every template variable to availableness.
