### ISSUE TITLE
Create API page in sphinx docs

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-jinja2#157]
The project started as tiny `jinja2` wrapper but it grows slowly.

http://aiohttp-jinja2.readthedocs.io/en/stable/ is cool but I feel a need for separate page with comprehensive descriptions for supported API.

http://aiohttp-jinja2.readthedocs.io/en/stable/#reference is too far from the beginning of text, and it is not full, e.g. http://aiohttp-jinja2.readthedocs.io/en/stable/#aiohttp_jinja2.setup doesn't reflect real `setup()` signature.

Any volunteer?
@bmwant maybe?

**Comment by bmwant** [comment]
sure, I will take a look

**Comment by asvetlov** [comment]
Fixed by #161
