### ISSUE TITLE
Welcome Samuel Colvin as the project collaborator

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-jinja2#158]
@samuelcolvin got write access to the repo.

I didn't ask Samuel for this and didn't make vote poll -- just added him.
Samuel is aiohttp member with write access already, I see his activity in `aiohttp-jinja2` project.
Pretty sure the project will have benefits from new Samuel position.

**Comment by jettify** [comment]
👍

**Comment by samuelcolvin** [comment]
:+1: great, thanks. Closing this issue.
