### ISSUE TITLE
Resolving named url while using subapps in aiohttp_jinja2

### ISSUE THREAD

**Issue by ansrivas** [aio-libs/aiohttp-jinja2#163]
Continuing from [here](https://stackoverflow.com/questions/46654773/resolving-named-url-while-using-subapps-in-aiohttp-jinja2) ..

I am trying to use aiohttp-jinja2 with app.add_subapp(). Unfortunately I am not able to figure out how to use `{{ url('named_url') }}` in case of subapps.

I followed the docs and now I am using it as following:

`main.py`

```python
app.router.add_route('GET', '/', Index)

app.add_subapp(r'/api/v1/todo', todos_app)
app['todos_app'] = todos_app
```

`index_handler.py`

```python
import aiohttp_jinja2
from aiohttp import web 

class Index(web.View):
    """Index page for the server."""

    @aiohttp_jinja2.template('index.html')
    async def get(self):
        """Return a simple page with urls."""
        todos_app = self.request.app['todos_app']
        return {
            'new_todo_url': todos_app.router['new_todo'].url_for(),
        }
```
And

`index.html`

```
<li class="list-group-item"><a href="{{ new_todo_url }}">New Todo</a></li>
```
I was wondering if there is a more efficient/better way to achieve this, by just using url('subapp_named_resource') ?

**Comment by ansrivas** [comment]
@asvetlov  suggested that `url_for` can become contexual w.r.t app `{{ url_for('todos_app', 'new_todo') }}` .

Quickly looking In the code 
https://github.com/aio-libs/aiohttp-jinja2/blob/f3ab03c3aa93d3b6c261beaaf0d8eaa542b5cb49/aiohttp_jinja2/helpers.py#L9 , this could become something like:
1. `def url_for(context, app_name, __route_name, **parts):`  or
2. part of keyword arguments and if not present, defaults to `app`. ?

**Comment by samuelcolvin** [comment]
Personally I think sub app routes should be available via `subapp:view-name`, which would require a `route_name` argument to `add_subapp`. To be honest, I thought this was already possible but apparently not.

Without that, the simplest solution would be to add a custom function, something like

```python
@jinja2.contextfunction
def my_url_for(context, __route_name, **parts):
    # whatever you want
    ...
    return url
env = aiohttp_jinja2.setup(app, loader=jinja2.FileSystemLoader('/path/to/templates/folder'))
env.gobals['url'] = my_url_for
```

**Comment by asvetlov** [comment]
Well, `subapp:view-name` naming looks attractive.
Thoughts about implementation details.
`:` form should start lookup from top-level app, sibling subapps are not supported.
Three level nesting should behave like  `subapp_a:subapp_b:view-name`

**Comment by samuelcolvin** [comment]
discussion of `subapp:view-name` at https://github.com/aio-libs/aiohttp/issues/2314

I'm closing this as I don't think it's an issue with aiohttp-jinja2, but @ansrivas if you have any more questions feel free to ask here.
