### ISSUE TITLE
jinja2 template path  dict in dict

### ISSUE THREAD

**Issue by pro-a-v** [aio-libs/aiohttp-jinja2#164]
## Long story short
jinja2 template wrong dict

 <li><a href="{{ url('poll', parts={'question_id': question.id}) }}">{{ question.question_text }}</a></li>
is a 
url = app.router[__route_name].url_for(**parts) ->  str(URL_PATTERN).format_map(EXPECT_DICT)

but we have   { 'parts' : {RIGHT_DICT} }    dict in dict
## Steps to reproduce
    myargs = {'path': {'question_id' : 1 }}
    var_err = str('/pool/{question_id}').format_map(myargs)
    var_ok = str('/pool/{question_id}').format_map(myargs['path'])

/usr/lib/python3.6/site-packages/aiohttp_jinja2/helpers.py

    if 'query_' in parts:
        query = parts.pop('query_')

    url = app.router[__route_name].url_for(**parts)

## Your environment

**Comment by pro-a-v** [comment]
https://github.com/aio-libs/aiohttp/blob/master/demos/polls/aiohttpdemo_polls/templates/index.html

**Comment by asvetlov** [comment]
Sorry, but your bug report is totally unclear.

**Comment by pro-a-v** [comment]
English not my native but i'll try to explain

if you look in example
https://github.com/aio-libs/aiohttp/blob/master/demos/polls/aiohttpdemo_polls/templates/index.html
you will see jinja template
<li><a href="{{ url('poll', parts={'question_id': question.id}) }}">{{
question.question_text }}</a></li>

in routes.py we define:

def setup_routes(app):
    app.router.add_get('/', index)
    app.router.add_get('/poll/{question_id}', poll, name='poll')


it setup route     /poll/{question_id}

then when we process such template we run code in aiohttp_jinja2/helpers.py

@jinja2.contextfunction
def url_for(context, __route_name, **parts):
    """
    filter for generating urls, see
    http://aiohttp.readthedocs.io/en/stable/web.html#reverse-url-constructing-using-named-resources

    Usage: {{ url('the-view-name') }} might become "/path/to/view" or
    {{ url('item-details', id=123, query={'active': 'true'}) }} might
become "/items/1?active=true".
    """

app = context['app']

query = None
if 'query_' in parts:
    query = parts.pop('query_')

url = app.router[__route_name].url_for(**parts)
if query:
    url = url.with_query(query)
return url

#################################

app.router[__route_name].url_for(**parts)   it's   a
str('/poll/{question_id}').format_map(parts)


and format_map expect simple dict

we have   { 'parts' : { 'question_id' : 1} }

and such construction doesn't work





2017-10-13 13:55 GMT+03:00 Andrew Svetlov <notifications@github.com>:

**Comment by asvetlov** [comment]
Re-read many times and still cannot figure out the problem.
