### ISSUE TITLE
jinja2 context processor middleware not useful in nested applications

### ISSUE THREAD

**Issue by skandalfo** [aio-libs/aiohttp-jinja2#193]
context_processors_middleware unconditionally sets request[REQUEST_CONTEXT_KEY] to the empty dictionary.

That means that, when nesting applications where both the parent and the child have been set to use jinja2 and context processors, anything added to the request by the parent's processors is cleared whenever a request is routed to the child app.

That prevents from composing context data in the request that comes from both apps.

To see why such composition is desirable, consider plain middlewares adding extra properties to the request, doing request['prop']=value. The handlers for the subapp will see all properties in the request set by the parent app as long as they are not overwritten in the child.

As request[REQUEST_CONTEXT_KEY][whatever]  is kind-of an equivalent of request[whatever], but for templates, it makes sense for its value to be merged in the subapp rather than replaced. The code needs to be modified so that request[REQUEST_CONTEXT_KEY] isn't reset if the key is already set.

I've seen this as an issue when sharing the same template loader in both the parent and the child apps. The child app wouldn't see results from the parent context processors if the child also had its own context processors.

**Comment by asvetlov** [comment]
Makes sense.
Would you make a Pull Request with fix?
