### ISSUE TITLE
Is it possible to add extensions to jinja2?

### ISSUE THREAD

**Issue by bonny1992** [aio-libs/aiohttp-jinja2#221]
Right now I'm trying to configure [pypugjs](https://github.com/kakulukia/pypugjs/) (which worked flawlessly with Flask) with this library.

I'm currently using the Jinja2 [configuration](https://github.com/kakulukia/pypugjs/blob/master/docs/installation.rst#jinja2) that can be found on pypugjs repo, it throws no errors but of course it's not set up with the app.

Please keep in mind that I'm not an expert with aiohttp or jinja2.

**Comment by asvetlov** [comment]
You can pass additional parameters into `aiohttp_jinja2.setup()` to configure `jinja2.Environment`.
See https://github.com/aio-libs/aiohttp-jinja2/blob/master/aiohttp_jinja2/__init__.py#L21-L36

**Comment by thiezn** [comment]
Had the same question, here's a more concrete example on how to do it with the jinja2_highlight plugin as an example.

```python
import aiohttp_jinja
import jinja2_highlight
import jinja2

template_folder = "/templates"
jinja2_extensions = [
    jinja2_highlight.HighlightExtension
]

aiohttp_jinja2.setup(
    app,
    loader=jinja2.FileSystemLoader(template_folder),
    extensions=jinja2_extensions,
)
```
