### ISSUE TITLE
Support async rendering

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp-jinja2#333]
`template()` and `render_template()` should be async functions, or for backwards compatibility new async versions of the functions should be added.

They should call `jinja2.Template.render_async()`, which also requires `enable_async` in the environment setup.

See:
https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment
https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Template.render_async
https://jinja.palletsprojects.com/en/2.11.x/api/#async-support

**Comment by Dreamsorcerer** [comment]
Currently, it looks like the only way to use the async functionality is like this:

```
template = aiohttp_jinja2.get_env(request.app).get_template("index.jinja")
return web.Response(text=await template.render_async(), content_type="text/html")
```

**Comment by Dreamsorcerer** [comment]
Given that passing enable_async breaks the existing functions, maybe a good way to handle backwards compatibility is just to switch the functions when enable_async is passed by the user.

e.g.
```
if kwargs.get("enable_async", False):
    aiohttp_jinja2.template = aiohttp_jinja2._template_async
    aiohttp_jinja2.render_template = aiohttp_jinja2._render_template_async
```

Or, something like that. Then all the user has to do is add `enable_async=True` to the `setup()` call.

**Comment by Dreamsorcerer** [comment]
@asvetlov I'm happy to work on this PR. Any thoughts on the correct way to implement it? Does my last comment seem reasonable?

**Comment by asvetlov** [comment]
I think we need separate functions for async mode.

If you are willing to work on it -- please go ahead
