### ISSUE TITLE
Deploy latest docs

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp-jinja2#401]
@asvetlov I've added the async functions to the docs, but it doesn't appear to be auto-deployed to the website. So, when you've got a moment, that should get deployed.

**Comment by webknjaz** [comment]
@Dreamsorcerer they are autodeployed under the `/latest` prefix (https://readthedocs.org/projects/aiohttp-jinja2/builds/12394487/). But when you open RTD you see stable  (https://aiohttp-jinja2.readthedocs.io/en/stable/) and need to switch version to https://aiohttp-jinja2.readthedocs.io/en/latest/.

**Comment by asvetlov** [comment]
The async render method is not shown on RTD because this commit was not released yet.
We need a technical bugfix release that updates RTD stable version.

Working on it.

**Comment by asvetlov** [comment]
Done
