### ISSUE TITLE
Make typing_extensions just optional dependency

### ISSUE THREAD

**Issue by mcepl** [aio-libs/aiohttp-jinja2#451]
`typing_extensions` package doesn’t have to be dependency for Python 3.8 and newer. [This patch](https://github.com/aio-libs/aiohttp-jinja2/files/6568183/stdlib-typing_extensions.patch.txt) makes the dependency just optional.

**Comment by Dreamsorcerer** [comment]
Feel free to make a PR. Please use a version check like this though:
https://github.com/aio-libs/aiohttp/blob/3.8/aiohttp/hdrs.py#L10-L13

And don't forget to adjust the dependencies as well:
https://github.com/aio-libs/aiohttp/blob/3.8/setup.py#L73

Thanks.

**Comment by mcepl** [comment]
Sorry, I am a maintainer of over 2000 packages at openSUSE, I really don't have time and energy to clone all those repositories. This patch is what you get. Feel free to modify however you want and I really cannot care less about the attribution and stuff.
