### ISSUE TITLE
Latest PyPI version is 0.8.0, opposing to 0.11.0 on github

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/aiohttp-jinja2#46]
It is a question, not an issue. Is it intentional? 
Thanks.

**Comment by asvetlov** [comment]
OOps. Looks like autobuild script is broken

**Comment by asvetlov** [comment]
Correction: it's not broken but just doesn't exist :(

**Comment by asvetlov** [comment]
Fixed by aiohttp-jinja2==0.12.0
