### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Masynchin** [aio-libs/aiohttp-jinja2#475]
aiohttp_jinja2\helpers.py:24: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1

aiohttp_jinja2\helpers.py:62: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1

**Comment by Masynchin** [comment]
I see this was solved in #455 but still in latest release. Maybe it should be bumped to 1.4.3?

**Comment by Dreamsorcerer** [comment]
Pushed 1.5, dropping support for Jinja2 <3.

**Comment by Masynchin** [comment]
Thanks <3
