### ISSUE TITLE
jinja2 package version clash when installed as part of connexion[aiohttp]

### ISSUE THREAD

**Issue by AaronRobson** [aio-libs/aiohttp-jinja2#478]
From https://github.com/aio-libs/aiohttp-jinja2/compare/v1.4.2...v1.5 I can see that the required version of `jinja2` that is required has changed from v2 to v3.
However this is a backwards incompatible change in the context of installing the connexion package with aiohttp support.
```bash
aaron@eleanor:~$ pip3 install connexion[aiohttp]
...
ERROR: flask 1.1.4 has requirement click<8.0,>=5.1, but you'll have click 8.0.1 which is incompatible.
ERROR: aiohttp-jinja2 1.5 has requirement jinja2>=3.0.0, but you'll have jinja2 2.11.3 which is incompatible.
...
```
And I would have therefore expected it to require a major version bump (i.e. be part of `v2.0.0`).

Please see my issue on the other repo: https://github.com/zalando/connexion/issues/1416

**Comment by Dreamsorcerer** [comment]
I did consider a major version bump, but I figured it wasn't necessary as the user-facing API has not changed. Perhaps I hadn't thought of this case, but a conflict of dependencies is pip's job to warn you, which it has. So, I'm not sure it's a real issue, just pin aiohttp-jinja2 to `<1.5` till they've added support for 3+.

I'm not sure if it's the right decision, but I can't take back a release. Feel free to provide additional reasoning for future reference though. Changing the minimum version of a dependency seems like a fairly common thing that doesn't usually require a major version bump.

Also, don't think the `click` conflict has anything to do with us.

**Comment by AaronRobson** [comment]
You make a fair point @Dreamsorcerer.

For others in a similar situation, try updating your pip version to benefit from its improved dependency resolver with:
```bash
pip install --upgrade pip==21.2.4
```
This has resolved the issue I was having.
