### ISSUE TITLE
AttributeError: module 'jinja2' has no attribute 'contextfunction'

### ISSUE THREAD

**Issue by ramicetty** [aio-libs/aiohttp-jinja2#561]
```
"/usr/local/lib/python3.8/site-packages/connexion/__init__.py", line 40, in <module>

 from .apis.aiohttp_api import AioHttpApi

  File "/usr/local/lib/python3.8/site-packages/connexion/apis/aiohttp_api.py", line 9, in <module>

    import aiohttp_jinja2

  File "/usr/local/lib/python3.8/site-packages/aiohttp_jinja2/__init__.py", line 24, in <module>

    from .helpers import GLOBAL_HELPERS

  File "/usr/local/lib/python3.8/site-packages/aiohttp_jinja2/helpers.py", line 23, in <module>

    @jinja2.contextfunction

AttributeError: module 'jinja2' has no attribute 'contextfunction'
```
Requirements that we are using currently

aiohttp>=3.7.4
aiohttp-swagger>=1.0.5
aiohttp-jinja2==1.4.2

Look like 1.4.2 is the latest as per github releases.

am i missing anything. Kindly help me.

**Comment by AlexVndnblcke** [comment]
If I'm correct the issue was introduced by a new version of jinja2. I've spotted changes for deprecated contextfunction in their changelog (https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0).

A quick patch would be to pin down the jinja2 version to <3.1.x

**Comment by ramicetty** [comment]
using aiohttp-jinja2==1.5  also worked for me. not sure why this release not updated in this repo.
