### ISSUE TITLE
Use of url() with params

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiohttp-jinja2#65]
This is the url:

`('*', '/users/password/edit/{token}', a.SetNewPassword, 'set_new_password')`

`url = self.request.app.router['set_new_password'].url_for(token=token)`

it works fine.

`{{ url('set_new_password', token=token) }}`

TypeError: url() got an unexpected keyword argument 'token'

https://github.com/aio-libs/aiohttp-jinja2/blob/master/aiohttp_jinja2/__init__.py#L30

url should be deprecated for url_for ?

**Comment by jettify** [comment]
fixed via https://github.com/aio-libs/aiohttp-jinja2/pull/84
