### ISSUE TITLE
Any plans for an aiohttp-chameleon

### ISSUE THREAD

**Issue by mikeckennedy** [aio-libs/aiohttp-jinja2#86]
Hi everyone,

Excellent work on aiohttp altogether. This isn't an issue per-say but wondering if anyone is planning on a chameleon version? I see you have jinja2 and mako.

**Comment by jettify** [comment]
Hi, there are no plans that I am aware of, but this kind of library should be strait forward to create using aiohttp-jinja2 and aiohttp-mako as example and do not require a lot of work.

**Comment by mikeckennedy** [comment]
Thanks. I'm asking because I might want to give it a try but not if others are on it! Ok, I'll have a look at those two libraries (that was my next step if you all say no one is pursuing it).
